### ISSUE TITLE
Отсутствует индикатор и сопроводительный текст о надежности пароля при смене пароля в попапе "Изменение пароля"

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#134]
**Предусловие:**

1.Открыть страницу https://familybudget.ddns.net/

2. Пользователь авторизован (например, имя пользователя: oneone, пароль: oneoneone!)
3.Перейти на страницу личного кабинета
**Окружение:**
Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.В "Настройках профиля" кликнуть "Сменить пароль"
2. В попапе "Изменение пароля" ввести корректный для смены пароль, например: Rhjjfkjjg1*
3.Осмотреть появление индикатора и текста о надежности пароля по полем ввода нового пароля
**ФР:**
Отсутствует индикатор и сопроводительный текст о надежности пароля при смене пароля в попапе "Изменение пароля"

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/92ab0c7f689b867238f494e16f41fd9e63bdc277/%D0%BD%D0%B5%D1%82%20%D0%B8%D0%BD%D0%B4%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D0%B0%20%D0%BD%D0%B0%D0%B4%D0%B5%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D0%B8%20%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8F%202023-06-18_17h14_21.jpg](url)

**ОР:**
Есть индикатор и сопроводительный текст о надежности пароля при смене пароля в попапе "Изменение пароля"

**Макет:**
[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/cd4d0e0e2b5bfc53cd6cbf37384530cfb5de93cc/%D0%BD%D0%B0%20%D0%BC%D0%B0%D0%BA%D0%B5%D1%82%D0%B5%20%D0%B5%D1%81%D1%82%D1%8C%20%D0%B8%D0%BD%D0%B4%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%20%D0%BD%D0%B0%D0%B4%D0%B5%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D0%B8%20%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8F%202023-06-18_17h14_59.jpg](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/45

**Comment by VolcharaMastering** [comment]
Согласен, что вроде надо, но увы. Ставлю как не критично. Проблема в том, что заданная в чек-листе требование "индикатор и сопроводительный текст о надежности пароля" включает огромный и тяжёлый процесс, а именно: подключение словарей и проверка пароля на "словарность", отслеживание Заглавных и строчных, проверка на наличие и букв и цифр и спецсимволов. На данном этапе решено (на командном созвоне) не тратить пока время. Достаточно просто проверки на спецсимволы.

**Comment by yareliance** [comment]
Закрываю пока раз не делаем, чтобы расхламить.
