### ISSUE TITLE
В полях Имя/Фамилия не проходит валидация при кол-ве символов >25

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#135]
**Предусловие:**
1.Войти на страницу https://familybudget.ddns.net/
2.Пользователь не авторизован
**Окружение:**
Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Зарегистрироваться"
2. Заполнить корректными данными поля логин и пароль, почту (например, логин: five, пароль: Rhjrjlbk1!, e-mail: five@five.ru)
3. Ввести в поле Имя/Фамилия последовательно:
26 символов: asdasdasdasdasdasdasdasdas
49 символов: asdasdasdasdasdasdasdasdasasdasdasdasdasdasdasdas
50 символов: asdasdasdasdasdasdasdasdasasdasdasdasdasdasdasdasd
**ФР:** Нельзя ввести в поле имя/фамилия больше 25 символов
Примечание: аналогично в ЛК при изменении имени/фамилии, при авторизованном пользователе

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/f97d6ccdd5f397f46ee94c7f86a0f669935ede7f/2023-06-18_20h18_40.jpg](url)

**ОР:** Можно ввести в поле имя/фамилия до 50 символов включительно

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/de9d3d34f2e0b52370dce331cbea2864fb04d734/2023-06-18_20h19_25.jpg](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/44

**Comment by VolcharaMastering** [comment]
сделано
