### ISSUE TITLE
Пустое поле email в ЛК проходит валидацию

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#136]
**Предусловие:**

1.Войти на страницу https://familybudget.ddns.net/

2.Пользователь авторизован
3. Войти в личный кабинет: клик на аватарку => перейти в личный кабинет
**Окружение:**
Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Изменить данные"
2. Очистить поле e-mail
3. Кликнуть "Сохранить данные"
**ФР:**
Пустое поле email в ЛК проходит валидацию

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/04c12de1f7f96fa7f0312b3ba431ad16475188a2/Screenshot_10.png](url)

**ОР:**
Пустое поле email в ЛК НЕ проходит валидацию

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/43

**Comment by VolcharaMastering** [comment]
сделано
