### ISSUE TITLE
Ретест. Поле email со спецсимволами (кроме -, _, @), количеством символов: 6, 130 и больше - проходят валидацию при регистрации и в ЛК

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#137]
**Предусловие:**

1.Войти на страницу https://familybudget.ddns.net/

2.Пользователь не авторизован
**Окружение:**
Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Зарегистрироваться"
2. Заполнить корректными данными поля логин и пароль (например, логин: five, пароль: Rhjrjlbk1!)
3. Ввести последовательно в поле e-mail:
reliance!*thtj@rjj.th
d@a.cc
130 символов: asdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasadasdasdasdaasdasdasdasdasdasdasdasdas@asdasdasd.sdasdasdasdasdasdasdas
131 символов: asdasdasdasdasdasdasasddasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdaasdasdasdasdasdasdasdas@asdasdasdasdas.asdasdasdasdasdasda
150 символов: asdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdasdaasdasdasdasdasdasdasd@sdasd.sdasdasdasdasdasdasdasdasdasdasdasdasdasdaasdasdasda
**ФР:**
Поле email со спецсимволами (кроме -, _, @), количеством символов: 6, 130 и больше - проходят валидацию при регистрации и в ЛК
Примечание: аналогично в ЛК при изменении e-mail
**ОР:**
Поле email со спецсимволами (кроме -, _, @), количеством символов: 6, 130 и больше НЕ проходят валидацию при регистрации и в ЛК

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/55d06575ccd4fd3a9f4dd1035f991b61084b05f1/Screenshot_9.png](url)

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/1560d988ce8b9e273b3b625484714aa117803884/2023-06-18_19h32_17.jpg](url)

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/cd42b789f32bf3d4e57ef2e04cc804bec399b867/2023-06-18_19h30_21.jpg](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/42

**Comment by VolcharaMastering** [comment]
Сделано!

**Comment by yareliance** [comment]
При ретесте все равно дает сохранить email со спецсимволами (кроме -, _, @), количеством символов: 6, 130 и больше как при изменеии в ЛК, так и при регистрации.

![Image](https://github.com/AcceleratorYandexPracticum/family_budget/assets/126873047/efcd140c-135d-4e93-966b-e5a01e448252)

**Comment by VolcharaMastering** [comment]
Опять сделано!
