### ISSUE TITLE
Кириллица проходит валидацию в поле Пароль при регистрации пользователя и изменении пароля в ЛК

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#139]
**Предусловие:**
1. Войти на страницу https://familybudget.ddns.net/
2.Пользователь не авторизован
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Зарегистрироваться"
2. В поле пароля попапа "Регистрация" ввести пароль кириллицей, например: мылонашею
**ФР:**
Кириллица проходит валидацию в поле Пароль при регистрации пользователя
Примечание: аналогично при изменении пароля в ЛК
**ОР:**
Пробел после введенных символов в поле логин, пароль убирается при снятии фокуса автоматически

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/9406db6ba62971b22ca84f0e543ee511e8f68082/Screenshot_4.png](url)

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/a24ffeb078af388dd901c71f25187c88c4ba26a0/2023-06-18_19h48_34.jpg](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/39

**Comment by VolcharaMastering** [comment]
Сделано
