### ISSUE TITLE
Можно ввести больше 25 символов в поле Логин в попапе "Авторизация", "Регистрация", странице ЛК

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#140]
**Предусловие:**

1. Войти на страницу https://familybudget.ddns.net/

2.Пользователь не авторизован
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Войти"
2. Ввести в поле логин последовательно:
26 символов: "asdasdasdasdasdasdasdasdas",
27 символов: "asdasdasdasdasdasdasdasdasd",
32 символа: "asdasdasdasdasdasdasdasdasdasdas".
**ФР:**
Можно ввести больше 25 символов в поле "логин" в попапе "Авторизация"
Примечание: аналогично можно ввести больше 25 символов в поле "логин" в попапе "Регистрация", странице ЛК
**ОР:**
Нельзя ввести больше 25 символов в поле "логин" в попапе "Авторизация"

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/b11567b22a821ad382277b478780ab4fc68ef1b4/Screenshot_3.png](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/38

**Comment by VolcharaMastering** [comment]
Сделано!
