### ISSUE TITLE
Пробел после данных в полях ввода не убирается при снятии фокуса

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#141]
**Предусловие:**

1.Войти на страницу https://familybudget.ddns.net/

2.Пользователь не авторизован
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Войти"
2. В поле логин попапа "Авторизация" ввести логин с пробелом после
3. Введите пароль с пробелом после
**ФР:**
Пробел после введенных символов в поле логин не удаляется, показывает ошибку "Введите правильный логин".
Пробел после введенных символов в поле пароль не удаляется, но если введен корректный логин, то при нажатии "Войти" пользователя авторизует.
**Примечание:** аналогично в попапе регистрации и ЛК поля логин и пароль, также пробел после e-mail при регистрации и в ЛК
**ОР:**
Пробел после введенных символов в поле логин, пароль убирается при снятии фокуса автоматически

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/515b3959f91d53e46e3b9f8189a88a7ce1f6379c/Screenshot_2.png](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/37

**Comment by VolcharaMastering** [comment]
Сделано. Но поле пароль оставил без изменений, т.к. там запрещать пароль... ну не правильно:)
