### ISSUE TITLE
Пробел перед данными в полях ввода не удаляется при снятии фокуса

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#142]
**Предусловие:**

1.Войти на страницу https://familybudget.ddns.net/

2.Пользователь не авторизован
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Войти"
2. В поле логин попапа "Авторизация" ввести логин с пробелом до
3. Введите пароль с пробелом до
**ФР:**
Пробел перед введенными символами в поле логин не удаляется, показывает ошибку "Введите правильный логин"
Пробел перед введенных символов в поле пароль не удаляется, но если введен корректный логин, то при нажатии "Войти" пользователя авторизует.
**Примечание:** аналогично в попапе регистрации и ЛК поля логин и пароль, также пробел после e-mail при регистрации и в ЛК
**ОР:**
Пробел перед введенными символами в поле логин, пароль убирается при снятии фокуса автоматически

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/069486e7d5b7ef1da1a12a6d1bdc8d02953c69c2/auth-login-space.png](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/36

**Comment by VolcharaMastering** [comment]
Сделано. Но поле пароль оставил без изменений, т.к. там запрещать пароль... ну не правильно:)
