### ISSUE TITLE
Личный кабинет: при нажатии на "Изменить данные" нельзя отказаться от редактирования

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#143]
**Предусловие:**

1.Войти на страницу https://familybudget.ddns.net/

2.Пользователь авторизован (например, имя пользователя: oneone, пароль: oneoneone!)
3. Перейти на страницу личного кабинета: клик на аватарку => перейти в личный кабинет
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Изменить данные"
2. Кликнуть "Сохранить данные"
**ФР:**
При нажатии "Изменить данные" есть возможность только отредактировать какое-нибудь поле, если не вносить изменения, то выйти из режима редактирования данных можно только обновлением страницы
**ОР:**
При нажатии "Изменить данные" можно отменить изменения без редактирования полей

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/9d98f3dc10ff9db636256cd3a7b803ccafe61dd1/lk-no-cancel-button-for-editing.png](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/28

**Comment by VolcharaMastering** [comment]
сделано. Работает по Esc
