### ISSUE TITLE
Профиль пользователя не удаляется при подтверждении удаления в попапе "Подтверждение удаления"

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#144]
**Предусловие:**

1. Адрес сервера https://familybudget.ddns.net/

2.Пользователь авторизован
3. Перейти на страницу личного кабинета
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Удалить профиль"
2. В попапе "Подтверждение удаление" кликнуть "Удалить профиль"
**ФР:**
После подтверждения удаления профиля не разлогинивает, пользователь остается в личном кабинете, может перемещаться по страницам, удаляются данные в личном кабинете (все, кроме пароля), по-прежнему можно заходить в ЛК, редактировать данные и т.д. Нельзя выйти из этого "удаленного" профиля => нельзя войти в новый профиль или зарегистрировать новый.
**Примечание:** в БД профиль удаляется и после очистки кэша браузера можно залогинится под другим пользователем
**ОР:**
После подтверждения удаления профиля пользователя разлогинивает и открывается страница лендинга для неавторизованного пользователя

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/f0c59f586c92c853f125a700ed82d0bdbef2c3f7/%D1%83%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F%20%D1%83%D0%B4%D0%B0%D0%BB%D1%8F%D0%B5%D1%82%20%D0%B8%D0%B7%20%D0%B1%D0%B0%D0%B7%D1%8B%20%D0%B0%20%D0%BD%D0%B0%20%D1%84%D1%80%D0%BE%D0%BD%D1%82%D0%B5%20%D0%BD%D0%B5%20%D0%B2%D1%8B%D1%85%D0%BE%D0%B4%D0%B8%D1%82%20%D0%B8%D0%B7%20%D0%BB%D0%BA%202023-06-18_18h26_02.mp4](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/27

**Comment by yareliance** [comment]
Возможно нужен текст ошибки, если пользователь пытается зайти под несуществующим/удаленным аккаунтом, сейчас визуально только спиннер крутится и ничего не происходит, и пользователю непонятно что происходит то ли вход не работает, то ли не то ввел.

https://github.com/AcceleratorYandexPracticum/family_budget/assets/126873047/a3d41476-d4fb-407b-9f2c-105924e01852

**Comment by VolcharaMastering** [comment]
Заведите, пожалуйста, это как отдельную ошибку. А именно что-то вроде "нет сообщения об ошибках на сервере" ну или что-то подобное. Сам по себе юзвер удаляется, происходит разлогирование и этот баг в корне не верен, т.к. функционал удаления пользователя и функционал вывода сообщения о том, что сервер вернул ошибку - две абсолютно разные вещи.
![изображение](https://github.com/AcceleratorYandexPracticum/family_budget/assets/96596719/dafbcfd7-fd57-4b72-8c16-094ea84523cd)

**Comment by yareliance** [comment]
Отдельный таск создан https://github.com/AcceleratorYandexPracticum/family_budget/issues/169
