### ISSUE TITLE
Рамка полей ввода данных не подсвечивается зеленым при вводе корректных данных в попапах "Авторизация", "Регистрация"

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#145]
**Предусловие:**

1.Войти на страницу https://familybudget.ddns.net/

2.Пользователь не авторизован
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть на кнопку "Войти" в шапке
2. В открывшемся попапе "Авторизация" ввести данные зарегистрированного пользователя: например, имя пользователя: oneone, пароль: oneoneone!
3. Закрыть попап и кликнуть на кнопку "Зарегистрироваться" в шапке или по кнопке "Зарегистрироваться" в попапе "Авторизация"
4. В попапе регистрации ввести корректные данные (например, "one" в поле логина)
**ФР:**
Рамка полей ввода данных НЕ подсвечивается зеленым при вводе корректных данных в попапах "Авторизация", "Регистрация"
**ОР:**
Рамка полей ввода данных подсвечивается зеленым при вводе корректных данных в попапах "Авторизация", "Регистрация"

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/ace1fa8b94835bab9483f2e288f292ecd502cf71/auth-field-no-highlight.png](url)

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/aa76f5a87c14f74616892f5418fca956e98778c1/%D0%BD%D0%B5%D1%82%20%D0%B7%D0%B5%D0%BB%D0%B5%D0%BD%D0%BE%D0%B9%20%D1%80%D0%B0%D0%BC%D0%BA%D0%B8%20%D0%B2%20%D0%BF%D0%BE%D0%BB%D1%8F%D1%85%20%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%202023-06-17_22h18_43.jpg](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/25

**Comment by VolcharaMastering** [comment]
Тут странная ситуация. Такого просто нет в макете....

**Comment by yareliance** [comment]
![Image](https://github.com/AcceleratorYandexPracticum/family_budget/assets/126873047/f412a6d3-32be-421a-a4ad-1d03bead83f6)

![Image](https://github.com/AcceleratorYandexPracticum/family_budget/assets/126873047/e11c88c0-fddc-4f6e-aee8-688fc3d422fa)

**Comment by yareliance** [comment]
(решили не делать 11.07.2023 tg) написала в фич-лист update https://docs.google.com/spreadsheets/d/1vvx-RsQeXfZ0uwrwp-jnXvxhhc9PmcBckEZ6fyuebNg/edit#gid=0
