### ISSUE TITLE
Клик на область вне попапа "Регистрация" закрывает его

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#147]
**Предусловие:**

1. Войти на страницу https://familybudget.ddns.net/

2.Пользователь не авторизован
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть на кнопку "Зарегистрироваться" в header
2. Кликнуть на область вне попапа
**ФР:**
Клик на область вне попапа "Регистрация" закрывает его

Примечание: со всеми попапами так происходит
**ОР:**
Клик на область вне попапа "Регистрация" НЕ закрывает его

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/d0771b701fa5619c90422c8d326df073064b26d3/%D0%BA%D0%BB%D0%B8%D0%BA%20%D0%B2%D0%BD%D0%B5%20%D0%BF%D0%BE%D0%BF%D0%B0%D0%BF%D0%B0%20%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F%20%D0%B7%D0%B0%D0%BA%D1%80%D1%8B%D0%B2%D0%B0%D0%B5%D1%82%20%D0%BF%D0%BE%D0%BF%D0%B0%D0%BF%202023-06-17_22h53_20.mp4](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/22

**Comment by VolcharaMastering** [comment]
См. выше. Баг не в этом)
