### ISSUE TITLE
При корректном заполнении полей и клике по "Зарегистрироваться" в попапе "Регистрация" происходит переход на попап "Авторизация"

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#148]
**Предусловие:**
1.Войти на страницу https://familybudget.ddns.net/
2.Пользователь не авторизован
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть на кнопку "Зарегистрироваться" в header
2. Заполнить корректно все поля (например, и отметить чек-бокс "Я даю своё согласие на обработку персональных данных и ознакомился c Политикой o конфиденциальности"
3.Кликнуть "Зарегистрироваться" внизу попапа
**ФР:**
При корректном заполнении полей и клике по "Зарегистрироваться" в попапе "Регистрация" происходит переход на попап "Авторизация"
Примечание: затем до очистке кэша попап "Регистрация" не окрывается, а вместо него все время открывается попап "Авторизация"
**ОР:**
При корректном заполнении полей и клике по "Зарегистрироваться" появляется попап "Регистрация прошла успешно!", при его закрытии происходит переход в личный кабинет

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/21

**Comment by VolcharaMastering** [comment]
Тут ситуация следующая. 
1. Ещё во втором месяце Мария сообщала, что вариант с автоАвторизацией реализовать не получается. На общем созвоне решили оставить переход на попап с авторизацией после регистрации (видимо не внесли в фич-лист).
2. "Примечание: затем до очистке кэша попап "Регистрация" не окрывается, а вместо него все время открывается попап "Авторизация"". Тут явно ошибка с фронтовой стороны. Её бы поместить отдельно. Правда не до очистки кеша, а достаточно обновить страницу ;-)

**Comment by yareliance** [comment]
Создала отдельно https://github.com/AcceleratorYandexPracticum/family_budget/issues/170
