### ISSUE TITLE
Клик на область вне попапов "Авторизация", "Изменение пароля", "Загрузить новое фото", "Подтверждение удаления" закрывает их

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#150]
**Предусловие:**
1.Открыть страницу https://familybudget.ddns.net/
2.Пользователь не авторизован
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть на кнопку "Войти" в шапке
2. Кликнуть в любую область за границами открывшегося попапа "Авторизция"
**ФР:**
Клик на область вне попапа "Авторизция" закрывает его
**ОР:**
Клик на область вне попапа "Авторизция" НЕ закрывает его
Примечание: аналогично с попапом "Изменение пароля", "Загрузить новое фото", "Подтверждение удаления" - клик на область за его пределами закрывает попап

[https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/d3372f30314e1a3bfbdc7b9473c47f7d504495a3/%D0%BA%D0%BB%D0%B8%D0%BA%20%D0%BD%D0%B0%20%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C%20%D0%B2%D0%BD%D0%B5%20%D0%BF%D0%BE%D0%BF%D0%B0%D0%BF%D0%B0%20%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%202023-06-17_19h55_11.mp4](url)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/24

**Comment by VolcharaMastering** [comment]
Может я что-то не знаю, но... На любом адекватном сайте должно быть именно так : ) Эта специально добавленный функционал

**Comment by yareliance** [comment]
Весь ожидаемый результат не придумывается QA) 
На сколько я помню, это обсуждалось еще на первых созвонах и доводы были, что это неудобно, когда пользователь все уже заполнил, кликнул мимо и все закрылось. 
Описание попапов изначально было вынесено в фич-листе отдельно и их описание сохранилось в обновленном фич-листе. Скрин прилагаю. 
Если решите с проджектами, что ок как есть сейчас, то это баг фич-листа, т.к. вся наша немногочисленная документация в виде фич-листа и макетов должна соответствовать друг другу и самому продукту.

![Image](https://github.com/AcceleratorYandexPracticum/family_budget/assets/126873047/e3b6de0a-7f73-47c1-8288-09e107b1917e)

**Comment by VolcharaMastering** [comment]
Давайте пока не будем это считать ошибкой. Предлагаю вместо этой добавить ошибку, что "при закрытии попапа, введённые данные удалились". Если будет время, то внесём изменения и сделаем, что закрытие попапа не повлияет на заполнение

**Comment by yareliance** [comment]
Создан https://github.com/AcceleratorYandexPracticum/family_budget/issues/171, в фич-листе изменила
