### ISSUE TITLE
Ретест. POST /api/users/set_password/ В ответе 204 no content вместо 200 ok с телом ответа

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#151]
**Описание:** в ответе должно возвращаться 200 ОК с данными о введенном и бывшем пароле в ответе
**Предусловие:** необходимо быть авторизованным пользователем
**Шаги воспроизведения:**
1.Задать в теле запроса new_password, re_new_password, current_password

{
  "new_password": "noviyparol",
  "re_new_password": "noviyparol",
  "current_password": "superslozhniparol"
}
2. Отправить запрос
Ожидаемый результат: в ответе 200 ОК, пароль изменен

{
  "new_password": "noviyparol",
  "re_new_password": "noviyparol",
  "current_password": "superslozhniparol"
}
Фактический результат: в ответе 204 no content, но пароль изменен

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/19

**Comment by yareliance** [comment]
Ошибка сохранилась, ОР прописан прямо в свагере, что ждем 200, а получаем 204.

![Image](https://github.com/AcceleratorYandexPracticum/family_budget/assets/126873047/df3e3199-9cfd-49e3-9ffa-06279c92e2b6)

**Comment by agatinet31** [comment]
Предыдущий и новый пароль не возвращается исходя из соображений безопасности и соответственно в ответе приходит код 204.

**Comment by yareliance** [comment]
Принято, максимум могу предложить в свагере в стандартном примере ответа слева также написать код 204, а не 200 раз мы его получаем.
