### ISSUE TITLE
Ретест. Нет интервала между ошибкой о длине символов в поле "Фамилия" и названием поля "Введите пароль повторно" при регистрации

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#160]
**Предусловие:**
1.Войти на страницу https://familybudget.ddns.net/
2.Пользователь не авторизован
**Окружение:**
Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Зарегистрироваться".
2. Ввести в поле Фамилия, например, 26 символов: asdasdasdasdasdasdasdasdas
**ФР:** Нет интервала между ошибкой о длине символов в поле "Фамилия" и названием поля "Введите пароль повторно" при регистрации
**Примечание:** как вариант уменьшить интервал между строками в тексте самой ошибки, что визуально подтянет нижнюю строку ошибки вверх
**ОР:** Есть интервал между ошибкой о длине символов в поле "Фамилия" и названием поля "Введите пароль повторно" при регистрации

![Image](https://github.com/AcceleratorYandexPracticum/family_budget/assets/126873047/fd0a1648-c11f-407e-bc02-c52938aba0a7)

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/51

Связан с https://github.com/AcceleratorYandexPracticum/family_budget/issues/140

**Comment by VolcharaMastering** [comment]
Изменил текст... Масштабирование дизайном не предусмотрено:(
