### ISSUE TITLE
Ретест. Опечатка в тексте ошибки при вводе символов русского алфавита в поле пароль при регистрации

### ISSUE THREAD

**Issue by yareliance** [AcceleratorYandexPracticum/family_budget#161]
**Предусловие:**
1.Войти на страницу https://familybudget.ddns.net/
2.Пользователь не авторизован
**Окружение:**
1.Chrome, Версия 114.0.5735.134; Windows 10 Pro ver. 22H2, разрешение экрана 2560х1440
2.Windows 10 Домашняя версия 22H2, сборка ОС 19045.3086,
Яндекс Браузер Версия 23.5.2.625 (64-bit), разрешение экрана 1920х1080
**Шаги:**
1.Кликнуть "Зарегистрироваться"
2. В поле пароля попапа "Регистрация" ввести пароль кириллицей, например: мылонашею
**ФР:**
Кириллица в тексте ошибки с одной "л".
**Примечание:** аналогично при изменении пароля в ЛК, возможно стоит скорректировать текст ошибки с проджектами, например, при регистрации на мейл пишет "Используйте только буквы (a–z, A–Z), цифры и символы ! @ # $ % ^ & * ( ) - _ + = ; : , . / ? \ | ` ~ { }"
**ОР:**
Кириллица в тексте ошибки с двумя "л".

https://qase-app-prod.s3.us-east-2.amazonaws.com/public/team/8a71a3c0308ee430dd312397a23ec2287b29f93f/attachment/9d1f9b4cb4310e9f93ca170d5ff6c0a143c3e99d/2023-07-12_21h10_42.jpg

Ссылка на qase.io: https://app.qase.io/defect/CSFB/view/52

Связано с: https://github.com/AcceleratorYandexPracticum/family_budget/issues/139

**Comment by VolcharaMastering** [comment]
💯 Позор безграмотным разрабам! Исправлено!
